api-test:
	curl -X POST https://mw1bjsboxb.execute-api.ap-northeast-2.amazonaws.com \
	--header "Content-Type: application/json" \
	-d '{ \
  		"startDate": "2017-08-01", \
  		"endDate": "2017-09-30", \
  		"timeUnit": "month", \
  		"category": "50000000", \
  		"keyword": "정장", \
  		"device": "", \
  		"gender": "", \
  		"ages": [] \
	}'